In [2]:
import numpy as np

In [4]:
a=np.asarray([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
print(a.shape)

(5,)


In [10]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [13]:
b[1][0]

2

In [14]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
#creating zeroes,ones,custom array
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#array of some constant
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [18]:
#identity matrix-size/square matrix
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#Random matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)


[[0.57051364 0.12145281 0.38940214]
 [0.78763024 0.85724008 0.78651578]]


In [28]:
randomMatrix[1,1:3]=1#slicing

In [29]:
print(randomMatrix[1,1:])

[1. 1.]


In [35]:
#set some rows and columns with any values
z=np.zeros((3,3),dtype=np.int64)
print(z)
z[1,:-1]=5
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [5 5 0]
 [0 0 0]]


In [36]:
#data types
print(z.dtype)

int64


In [39]:
#mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

#element wise operations
print(x,y)
print(x+y)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [43]:
print(x*y)
print(np.multiply(x,y))

print(x/y)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [44]:
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [45]:
#multiplications of vectors
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

print(a.dot(b))

30


In [46]:
print(a)

[1 2 3 4]


In [48]:
print(sum(a))

10


In [49]:
print(x)

[[1 2]
 [3 4]]


In [53]:
print(np.sum(x,axis=0))

[4 6]


In [54]:
print(np.sum(x,axis=1))

[3 7]


In [55]:
#stacking of arrays
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [59]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [66]:
#reshape a numpy array
print(a)
print(a.shape)
a=a.reshape((4,-1))
print(a)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
